repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.8.10
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      stages: [commit]
# -   repo: local
#     hooks:
#     - id: pytest
#       name: pytest
#       language: system
#       entry: pytest -v -s
#       always_run: true
#       pass_filenames: false
#       stages: [commit]
